# Generated by Django 3.2.6 on 2021-08-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classify',
            name='class_name',
            field=models.CharField(default='添加分类', max_length=30),
        ),
        migrations.AlterField(
            model_name='classify',
            name='tag',
            field=models.CharField(default='介绍网站', max_length=500),
        ),
    ]
