# Generated by Django 3.2.6 on 2021-08-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_auto_20210828_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='title',
            field=models.CharField(default='暂无标题', max_length=100),
        ),
    ]
