# Generated by Django 3.2.6 on 2021-08-28 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0004_data_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='classify_id',
            field=models.IntegerField(default=0, max_length=500),
        ),
    ]
